apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose.dev.yml
    kompose.version: 1.37.0 (HEAD)
  labels:
    io.kompose.service: analytics
  name: analytics
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: analytics
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -f docker-compose.dev.yml
        kompose.version: 1.37.0 (HEAD)
      labels:
        io.kompose.service: analytics
    spec:
      containers:
        - env:
            - name: DATABASE_URL
              value: postgres://user:password@db/xeodocs_db?sslmode=disable
            - name: INFLUXDB_BUCKET
              value: analytics
            - name: INFLUXDB_ORG
              value: xeodocs
            - name: INFLUXDB_TOKEN
              value: my-super-secret-auth-token
            - name: INFLUXDB_URL
              value: http://influxdb:8086
            - name: JWT_SECRET
              value: your-secret-key
            - name: KAFKA_BROKERS
              value: kafka:29092
            - name: PORT
              value: "80"
          image: xeodocs/analytics
          name: analytics
      restartPolicy: Always
