apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose.dev.yml
    kompose.version: 1.37.0 (HEAD)
  labels:
    io.kompose.service: kafka-ui
  name: kafka-ui
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: kafka-ui
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -f docker-compose.dev.yml
        kompose.version: 1.37.0 (HEAD)
      labels:
        io.kompose.service: kafka-ui
    spec:
      containers:
        - env:
            - name: KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS
              value: kafka:29092
            - name: KAFKA_CLUSTERS_0_NAME
              value: local
          image: provectuslabs/kafka-ui:latest
          livenessProbe:
            exec:
              command:
                - curl -f http://localhost:8080 || exit 1
            failureThreshold: 3
            periodSeconds: 30
            timeoutSeconds: 10
          name: kafka-ui
          ports:
            - containerPort: 8080
              protocol: TCP
      restartPolicy: Always
