apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose.dev.yml
    kompose.version: 1.37.0 (HEAD)
  labels:
    io.kompose.service: project
  name: project
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: project
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -f docker-compose.dev.yml
        kompose.version: 1.37.0 (HEAD)
      labels:
        io.kompose.service: project
    spec:
      containers:
        - env:
            - name: DATABASE_URL
              value: postgres://user:password@db/xeodocs_db?sslmode=disable
            - name: JWT_SECRET
              value: your-secret-key
            - name: PROJECT_PORT
              value: "80"
          image: xeodocs/project
          name: project
      restartPolicy: Always
