apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose.dev.yml
    kompose.version: 1.37.0 (HEAD)
  labels:
    io.kompose.service: e2e
  name: e2e
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: e2e
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -f docker-compose.dev.yml
        kompose.version: 1.37.0 (HEAD)
      labels:
        io.kompose.service: e2e
    spec:
      containers:
        - env:
            - name: ANALYTICS_SERVICE_URL
              value: http://analytics:80
            - name: AUTH_SERVICE_URL
              value: http://auth:80
            - name: BUILD_SERVICE_URL
              value: http://build:80
            - name: GATEWAY_URL
              value: http://gateway:12020/v1
            - name: LOGGING_SERVICE_URL
              value: http://logging:80
            - name: PROJECT_SERVICE_URL
              value: http://project:80
            - name: REPOSITORY_SERVICE_URL
              value: http://repository:80
          image: xeodocs/e2e
          name: e2e
      restartPolicy: Always
