apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose.dev.yml
    kompose.version: 1.37.0 (HEAD)
  labels:
    io.kompose.service: gateway
  name: gateway
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: gateway
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -f docker-compose.dev.yml
        kompose.version: 1.37.0 (HEAD)
      labels:
        io.kompose.service: gateway
    spec:
      containers:
        - env:
            - name: ANALYTICS_SERVICE_URL
              value: http://analytics:80
            - name: AUTH_SERVICE_URL
              value: http://auth:80
            - name: BUILD_SERVICE_URL
              value: http://build:80
            - name: GATEWAY_PORT
              value: "12020"
            - name: LOGGING_SERVICE_URL
              value: http://logging:80
            - name: PROJECT_SERVICE_URL
              value: http://project:80
          image: xeodocs/gateway
          name: gateway
          ports:
            - containerPort: 12020
              protocol: TCP
      restartPolicy: Always
