apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose.dev.yml
    kompose.version: 1.37.0 (HEAD)
  labels:
    io.kompose.service: scheduler
  name: scheduler
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: scheduler
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -f docker-compose.dev.yml
        kompose.version: 1.37.0 (HEAD)
      labels:
        io.kompose.service: scheduler
    spec:
      containers:
        - env:
            - name: DATABASE_URL
              value: postgres://user:password@db/xeodocs_db?sslmode=disable
            - name: JWT_SECRET
              value: your-secret-key
            - name: LOGGING_SERVICE_URL
              value: http://logging:80
            - name: PROJECT_SERVICE_URL
              value: http://project:80
            - name: RABBITMQ_URL
              value: amqp://guest:guest@rabbitmq:5672/
          image: xeodocs/scheduler
          name: scheduler
      restartPolicy: Always
